# Generated by Django 5.0.6 on 2024-05-28 13:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uu_id', models.UUIDField(default=uuid.uuid4)),
                ('title', models.CharField(max_length=225)),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
                ('genre', models.CharField(choices=[('action', 'Action'), ('comedy', 'Comedy'), ('drama', 'Drama'), ('horror', 'Horror'), ('romance', 'Romance'), ('sci-fi', 'Sci-Fi'), ('fantasy', 'Fantasy')], max_length=100)),
                ('image_card', models.ImageField(upload_to='movies_images/')),
                ('image_cover', models.ImageField(upload_to='movies_images/')),
                ('video', models.FileField(upload_to='movies_videos/')),
                ('movie_views', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
